Numpy - Numerical Python

Advantages of Numpy Arrays:

1.   Allows several Mathematical Operation
2.   Faster Operations



    

In [2]:
import numpy as np

#List vs Numpy - Time Taken


In [3]:
from time import process_time

Time taken by list

In [4]:
list1 = [i for i in range(1000000)]

start_time = process_time()

list2 = [i+10 for i in list1]

total_time = process_time() - start_time

print(total_time)

0.07390037999999999


In [5]:
np_array = np.array([i for i in range(1000000)])

start_time = process_time()

np_array += 5

total_time = process_time() - start_time

print(total_time)

0.0013347790000000082


#Numpy Arrays

In [8]:
# list
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [51]:
# numpy
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
type(arr1)

[1 2 3 4 5]


numpy.ndarray

In [14]:
arr1.shape

(5,)

In [15]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
type(arr2)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

#Initial placeholders in numpy arrays

In [40]:
# array of zeros
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
# array of ones
arr = np.ones((3,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
# array of identity matrix, which means all the diagnal values should be 1
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
# array of particular values
arr = np.full((3, 4), 8)
print(arr)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [44]:
# array of random values
arr = np.random.random((3, 4))
print(arr)

[[0.08800313 0.38969159 0.06507128 0.71842788]
 [0.49457641 0.96729074 0.84908272 0.1233977 ]
 [0.45125947 0.71750713 0.30986147 0.6035261 ]]


In [45]:
# array of random values of integers
arr = np.random.randint(0, 10, (3, 4))
print(arr)

[[9 1 8 8]
 [3 7 3 6]
 [1 2 3 9]]


In [49]:
# array of evenly spaced values with specifying the number of values
arr = np.linspace(8, 30, 5)
print(arr)

[ 8.  13.5 19.  24.5 30. ]


In [47]:
# array of evenly spaced values with specifying the steps
arr = np.arange(10, 30, 5)
print(arr)

[10 15 20 25]


In [54]:
# convert a list or tuple to numpy array
list1 = [8, 10, 12, 27, 28, 30]

arr = np.asarray(list1)
print(arr)
print(type(arr))

[ 8 10 12 27 28 30]
<class 'numpy.ndarray'>


#Analysing a numpy array

In [85]:
arr = np.random.randint(8, 100, (4, 5))

print(arr)

[[81 31 79 96 96]
 [81 28 58 93 49]
 [59 57 39 96 71]
 [80 72 48 89 73]]


In [86]:
# transporse an array
print(arr.T)

[[81 81 59 80]
 [31 28 57 72]
 [79 58 39 48]
 [96 93 96 89]
 [96 49 71 73]]


In [60]:
# get datatype of an array
print(arr.dtype)

int64


In [62]:
# array dimension (shape)
print(arr.shape)

(4, 5)


In [63]:
# number of dimension
print(arr.ndim)

2


In [64]:

print(arr.itemsize)

8


In [65]:
# total size of an array
print(arr.size)

20


In [68]:
# flattening the whole array
print(arr.flatten())

[90 58 25 66 54 73 20 11 27 46 99 95 25 32 13  8 25 27 48 17]


In [70]:
# reshaping an array dimension
print(arr.reshape((2, 10)))

[[90 58 25 66 54 73 20 11 27 46]
 [99 95 25 32 13  8 25 27 48 17]]


#Arithmetic Operations in numpy array

In [71]:
a = np.random.randint(10, 20, (3,3))
b = np.random.randint(20, 30, (3,3))
print(a)
print(b)

[[19 14 19]
 [12 11 10]
 [15 18 16]]
[[24 21 26]
 [20 22 23]
 [29 23 28]]


Using +, -, *, /, //


In [72]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)

[[43 35 45]
 [32 33 33]
 [44 41 44]]
[[ -5  -7  -7]
 [ -8 -11 -13]
 [-14  -5 -12]]
[[456 294 494]
 [240 242 230]
 [435 414 448]]
[[0.79166667 0.66666667 0.73076923]
 [0.6        0.5        0.43478261]
 [0.51724138 0.7826087  0.57142857]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


Using inbuild functions of numpy


In [77]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[43 35 45]
 [32 33 33]
 [44 41 44]]
[[ -5  -7  -7]
 [ -8 -11 -13]
 [-14  -5 -12]]
[[456 294 494]
 [240 242 230]
 [435 414 448]]
[[0.79166667 0.66666667 0.73076923]
 [0.6        0.5        0.43478261]
 [0.51724138 0.7826087  0.57142857]]


#Array Manipulation

In [87]:
arr = np.random.randint(0, 10, (2,3))
print(arr)
print(arr.shape)

[[3 8 0]
 [9 8 6]]
(2, 3)


In [88]:
trans = np.transpose(arr)
print(trans)
print(trans.shape)


[[3 9]
 [8 8]
 [0 6]]
(3, 2)


In [89]:
print(arr.T)

[[3 9]
 [8 8]
 [0 6]]
